[project]
name = "apscheduler-metrics"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "apscheduler>=3.11.0",
    "prometheus-client>=0.24.1",
]
